hooks:
  before:init:
    - yarn lint
    - yarn test
git:
  commit: true
  commitMessage: Release ${version}
  tag: true
  tagName: "${version}"
  tagAnnotation: Release ${version}
  push: true
npm:
  publish: false
github:
  release: true
  releaseName: Release ${version}
  # releaseNotes:
  tokenRef: GITHUB_TOKEN
