
name: Ship js Manual Prepare
on: deployment
jobs:
  manual_prepare:
    runs-on: Ubuntu-latest
    steps:
      - uses: JasonEtco/smee-action@master
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-node@master
      - run: yarn install
      - run: |
            git config --global user.email "dkimura@bdd.xyz"
            git config --global user.name "dkimura"
      - run: yarn release:prepare --yes --no-browse
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
